### ISSUE TITLE
doesn't work 

### ISSUE THREAD

**Issue by Razzy52** [Rdmo1/Hazard-Token-Grabber-V3#1]

**Comment by qPhantasm** [comment]
he probably needs more information instead of just "isn't working"

**Comment by Rdmo1** [comment]
ill fix it if i can also im updating neptune

**Comment by qPhantasm** [comment]
> ill fix it if i can also im updating neptune
> 

neptune's a logger, bro you chatted with me on disc and proofed it 💀

**Comment by Rdmo1** [comment]
fixed it try it now
